apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: v1
data:
  PGHOST: "34.221.5.136"
  PGUSER: "bukanebi"
  PGDATABASE: "Rentapp"
  PGPASSWORD: "bukalapak"
  PGPORT: "5439"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: vuetest-maps
  namespace: sample

---
apiVersion: v1
kind: Service
metadata:
  name: vuetest-ui
  namespace: sample
  labels:
    app: vuetest
    tier: frontend
spec:
  selector:
    app: vuetest
    tier: frontend
  type: LoadBalancer
  ports:
    - name: serviceport
      port: 8989
      targetPort: 80
      nodePort: 31648

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuetest-ui
  namespace: sample
spec:
  selector:
    matchLabels:
      app: vuetest
      tier: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
      app: vuetest
      tier: frontend
      annotations:
        date: "`date +'%s'`"
    spec:
      containers:
        - name: vuetest
          image: bukanebi/vuetest-front-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: vuetest-maps
