apiVersion: v1
kind: Namespace
metadata:
  name: sample

---
apiVersion: v1
kind: Service
metadata:
  name: vuetest-ui
  namespace: sample
  labels:
    app: vue-test
    tier: frontend
spec:
  selector:
    app: vue-test
    tier: frontend
  type: LoadBalancer
  ports:
    - name: serviceport
      port: 8989
      targetPort: 80
      nodePort: 31647

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuetest-ui
  namespace: sample
spec:
  selector:
    matchLabels:
      app: vue-test
      tier: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vue-test
        tier: frontend
      annotations:
        date: "`date +'%s'`"
    spec:
      containers:
        - name: vue-test
          image: bukanebi/vuetest-front-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
